### ISSUE TITLE
fetch following/follower list [enhancement]

### ISSUE THREAD

**Issue by lukaswelinder** [krstffr/meteor-instagram-fetcher#10]
Reading the Instagram API, I'm not even sure if this can be done on users other than yourself. 

However, I'm not mistaken in my understanding that this extension can only fetch user info & feed, correct?

I'm going to be giving it a go, and if it works out I'll submit a pull request. Thanks for the extension.

**Comment by krstffr** [comment]
You're correct in that this package currently can't fetch user followers/following, so a PR with these features would be great!

(If there are API endpoints for this.)



–

Kristoffer Klintberg
krstffr@gmail.com
+46 (0) 737 771 771www.newdocument.io

**Comment by lukaswelinder** [comment]
@krstffr Further reading has lead me to the conclusion that there is no endpoint for fetching the following list for users other than self. Sure would have been convenient.

Ended up writing a script for tasker on Android. My app now relies on a rasberry pi...

**Comment by krstffr** [comment]
Ok, that's a shame but cool that you found the Android/Pi solution!
