### ISSUE TITLE
access token not defined in basic usage

### ISSUE THREAD

**Issue by likkhian** [krstffr/meteor-instagram-fetcher#14]
after installing the package, I tried the basic usage example, and pasted the code in my main.js on the backend. It crashed out, and it seemed that the problem was with the line `check( options.token, String );` There is no token defined in the variable 'options'.

**Comment by krstffr** [comment]
Yeah, sorry, this package was made before meteor supported NPM and before Instagram changed their API. I recommend using some of the Instagram NPM-packages!

(I will update the readme)
