### ISSUE TITLE
Settings info in the README file

### ISSUE THREAD

**Issue by michalvalasek** [krstffr/meteor-instagram-fetcher#2]
Hello,

it would be nice if you could add information about the required configuration variables ("InstagramAPI") to the README file. 

Thanks for your effort!

**Comment by krstffr** [comment]
Hi!

I've added a short explanation now to the README file. Makes sense?

Thanks for pointing this out!

**Comment by michalvalasek** [comment]
Cool, thanks!

**Comment by krstffr** [comment]
Also, it would be quite easy to add more functionality to this package, I've just not gotten around to it since this was all I needed for a small project I was working on some time ago. Let me know if you need something specific and I'll see what I can do! @michalvalasek
