### ISSUE TITLE
Instagram self feed

### ISSUE THREAD

**Issue by maurop123** [krstffr/meteor-instagram-fetcher#5]
I'm working on developing this feature: https://instagram.com/developer/endpoints/users/

Once complete, I'll issue a pull request. Any tips are appreciated

**Comment by krstffr** [comment]
Hi! I'm not exactly sure what data exactly you want to fetch. However, this package could be refactored quite a bit from it's current state! Right now there are only 2 end points supported, and there's quite a bit of code duplication going on already, which could be improved.

So I can't really give you any tips right now, however if I get some time I will start thinking about a more sane way of structuring this package for future improvements! And when I've done that I'll let you know :)

**Comment by krstffr** [comment]
Hey @maurop123 I actually went ahead and fixed what you needed (I hope).

Checkout readme for more info on how to do what you want.
